name: BanSystem
main: bansystem\BanSystem
version: 1.0.3
authors: [xXSuperFrostyXx, randy128gamer, FlatterGnat9702]
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: A ban system that allows to temporarily/permanently ban/mute/block and kick players/IP address.